# Generated by Django 5.0.7 on 2024-07-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_user_profile'),
        ('store', '0005_profile_default_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
